/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojainformatica.view;

import DAO.ComputadoresDAO;
import com.mycompany.lojainformatica.domain.model.Computador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas Andrade
 */
public class ConsultaLojainformatica extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaLojainformatica
     */
    public ConsultaLojainformatica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCampoProcessador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Processador");

        jLabel2.setText("Consultar Computadores");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_COMPUTADOR", "Marca", "HD", "Processador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampoProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnAdicionar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExcluir)
                        .addComponent(btnAtualizar)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnBuscar))
                    .addComponent(txtCampoProcessador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if(txtCampoProcessador.getText().trim().isEmpty()){
            atualizarTabela();
        }else {
            String processador = txtCampoProcessador.getText();

            //Chamar a DAO para pesquisar na tabela notafiscal pelo numeroNota
            ArrayList<Computador> produtos = ComputadoresDAO.buscarPorProcessador(processador);

            DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
            modelo.setRowCount(0);

            for (Computador produto : produtos) {
                modelo.addRow(new String[]{
                        String.valueOf(produto.getIdComputador()),
                        String.valueOf(produto.getMarca()),
                        String.valueOf(produto.getHD()),
                        String.valueOf(produto.getProcessador())
                });

            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        CadastrarComputadores novaJanela = new CadastrarComputadores(); //Deixa a tela cadastro visivel para add mais um computador
        novaJanela.setVisible(true);

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        //1º Passo = Resgatar a linha e mandar para um objeto
        int linhaSelecionada = Table.getSelectedRow();

        //2º acessar a camada Model da tabela
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();

        //3º resgatar valores da linha selecionada

        int id = Integer.parseInt(String.valueOf(modelo.getValueAt(linhaSelecionada, 0).toString()));

        String marcaSelecionado = modelo.getValueAt(linhaSelecionada, 1).toString() ;

        String hdSelecionado =  modelo.getValueAt(linhaSelecionada, 2).toString() ;

        String processadorSelecionado =  modelo.getValueAt(linhaSelecionada, 3).toString() ;

        //4º Passar dados para o objeto
        Computador objAlterar =
        new Computador(id, marcaSelecionado,hdSelecionado, processadorSelecionado);

        //5º Passar o objeto para a tela de alteração
        CadastrarComputadores novaJanela = new CadastrarComputadores(objAlterar); //Deixa a tela cadastro visivel para add mais um computador
        novaJanela.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //1º Passo = Resgatar a linha e mandar para um objeto
        int linhaSelecionada = Table.getSelectedRow();

        //2º acessar a camada Model da tabela
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();

        //3º resgatar valores da linha selecionada
        int idSelecionado = Integer.parseInt(
                            modelo.getValueAt(linhaSelecionada, 0).toString());

        //4º Passo - Mandar o ID para a DAO excluir
        boolean retorno = ComputadoresDAO.excluir(idSelecionado);

        if(retorno){
            JOptionPane.showMessageDialog(rootPane, "Sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Falha!");
        }

        //Método para atualizar a tabela
        atualizarTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void atualizarTabela(){

        //Chamar a DAO para consultar notas do banco
        ArrayList<Computador> listaRetorno = ComputadoresDAO.listar();

        //Para cada item na lista, vou adicionar à tabela

        if (listaRetorno != null) {
        DefaultTableModel modelo = (DefaultTableModel) Table.getModel();
        modelo.setRowCount(0);

        for (Computador item : listaRetorno) {
            modelo.addRow(new String[]{
                String.valueOf(item.getIdComputador()),
                String.valueOf(item.getMarca()),
                String.valueOf(item.getHD()),
                String.valueOf(item.getProcessador())
            });

        }

    }else{
            JOptionPane.showMessageDialog(this, "Não foi encontrado nenhum registro");
        }

    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaLojainformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaLojainformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaLojainformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaLojainformatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaLojainformatica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCampoProcessador;
    // End of variables declaration//GEN-END:variables
}
